### ISSUE TITLE
Config generation in entrypoint might be broken

### ISSUE THREAD

**Issue by notgne2** [ropenttd/docker_openttd#10]
when launching a new container I get no base config, the server just launches without it, testing the command to generate it with docker exec gives me this

```
openttd@30061a15533a:~$ timeout -t 3 openttd -D
timeout: invalid option -- 't'
Try 'timeout --help' for more information
```

**Comment by luaduck** [comment]
Pretty sure this is being caused by a change to the timeout binary. I'll push a fix now.

**Comment by alexdawn** [comment]
I'm still getting this issue

**Comment by duckfullstop** [comment]
> I'm still getting this issue, that the entrypoint is not generating a config

Can you post your startup logging?
