### ISSUE TITLE
Docker file for X11-forwarding

### ISSUE THREAD

**Issue by joddm** [ropenttd/docker_openttd#13]
Hi,

As I understand this is only for the server mode?

How would you modify this to be able to play in Docker? I already have set up XQuartz, so I just need to get the build to also include everything that I need

Cheers

**Comment by duckfullstop** [comment]
This image is indeed intended for running as a server only.

If you want to fiddle with the binary directly, you'll need to override the entrypoint to `/app/bin/openttd`, which will avoid running the entrypoint script.

You could _try_ forwarding the local display with the following environment variables:

```
-e DISPLAY=$DISPLAY
-v /tmp/.X11-unix:/tmp/.X11-unix
```

but I make absolutely no guarantees that this will work. With that said, if you do manage to get it working, please let me know and I'll add your findings to the readme (and maybe add a special flag to the entrypoint for your usecase)
