### ISSUE TITLE
Supported Architectures

### ISSUE THREAD

**Issue by brucelong** [ropenttd/docker_openttd#18]
I went to run the container on a Pi 4, and realized that there is no ARM64 image for this container. Is there any plan to add support for this in the future?

**Comment by duckfullstop** [comment]
Better late than never, I'm taking a look into this now.

**Comment by duckfullstop** [comment]
All done! We now ship both _arm64_ and _amd64_ architectures - see the [readme](https://github.com/ropenttd/docker_openttd/blob/master/readme.md) for more information. The way this is currently being built isn't perfect as it uses qemu to emulate _arm64_ on the Actions runner (and it takes nearly an hour to complete a build), but that's not easily fixable unless someone either contributes an ARM runner, or Github adds ARM support to the runners.

If you have any issues with the arm64 build, please drop a comment.
