### ISSUE TITLE
Config File Version

### ISSUE THREAD

**Issue by Sheorath** [ropenttd/docker_openttd#19]
Hi the server works so far, but I think it got the wrong version.
If I look into the generated config file I see the following under the VERSION section

[version]
version_string = 1.10.1
version_number = 1A086D64

This indicated a version from 2020 I assume, is this intended?
Greetings

**Comment by duckfullstop** [comment]
If I remember correctly, the configuration values under the [version] flag are ignored at runtime - is the server broadcasting the correct version to clients (i.e can you join it)?

**Comment by Sheorath** [comment]
Nope, the Openttd tells me wrong version and on the [Website](https://servers.openttd.org/listing) I can see the broadcasted version
<img width="211" alt="Bildschirm­foto 2023-02-11 um 17 31 58" src="https://user-images.githubusercontent.com/99042500/218269522-4ebb4608-443a-410c-9e6c-e7f39804e661.png">

This Docker Image is about some vanilla server, right?

**Comment by duckfullstop** [comment]
Issue identified, working on the fix now.

**Comment by duckfullstop** [comment]
Can you confirm whether this is fixed properly once [the build finishes](https://github.com/ropenttd/docker_openttd/actions/runs/4152244138/jobs/7183071476)?

**Comment by duckfullstop** [comment]
Closing as presumed fixed (build logs show better traces now!).

**Comment by Sheorath** [comment]
yes works, many thanks!
