### ISSUE TITLE
/config/save/ not found...

### ISSUE THREAD

**Issue by produktchef** [ropenttd/docker_openttd#4]
Hi guys,

I'm really struggling to get this image to load a saved game. I'm fairly new to Docker so i'm probably doing something stupid. I'd really appreciate some help!

I'm running:
`docker run -d --name openttd -p 3979:3979/tcp -p 3979:3979/udp -e savegame=autosave -v ~/.openttd:/config:rw redditopenttd/openttd:latest` 

Without the argument `e loadgame=true` the logs show:

> loadgame not set - starting new game

...and then proceeds to generate a new map.

With -e loadgame=true in the command, if I look at the docker logs of the container, i'm just hitting the error:

> /config/save/ not found...

If I remove both `-e` arguments, the container loads up and the openttd.cfg file that's being mounted is working as expected; the server is named correctly, with all the correct configuration and map size etc. I just can't find autosaves or explicit saved game files (e.g. `-e savegame=mysavedgame.sav`)

Things I've tried:

1. I've ensured there is a /save/ folder within ~/.openttd folder that contains the .sav files.
2. I've chown'd (root:root and robin:robin) and chmoded the hell out of everything in case it was permissions and ownership related.
3. The .openttd folder that i'm mounting lives in my /home/robin/ user folder, and i've tried running docker as robin with sudo and as root.
4. Explicitly loading just the openttd.cfg file and the save directory as two separate -v arguments as described in luaduck's latest readme commits.

Cheers,
Robin

**Comment by produktchef** [comment]
Hi Lua,

Thanks for getting back to me.

Yep! Getting there. Passing "savename" instead led me to a NewGRF failure message. I've sorted those out and now it's loading the game.

One issue, I'm getting a "save failed" message on save now. I assume this is due to permissions.

> dbg: [sl] Game Save Failed
> File not writeable
> ERROR: Autosave failed

Any chance you can advise, please?

**Comment by produktchef** [comment]
Aha! Chownd the filesystem and it's now working perfectly!

**Comment by luaduck** [comment]
Awesome! I will probably update the readme / entrypoint script to be a little clearer, because this is confusing behaviour that is only really decipherable by reading the script.

**Comment by luaduck** [comment]
I've made some changes in the above commit; I'll rebuild the image tonight with the change. In summary, I've changed the `savegame` variable to actually do what it says on the box instead of its previous two-variable behaviour (with the extra `savename` variable).

**Comment by Rehaell** [comment]
I have the same issue, reading the readme here and the one on the docker i fail to understand which variable i need to use, should i use the loadgame + savename, or the savegame as per the one in the docker?

**Comment by luaduck** [comment]
This has been massively improved by #8, so I'm going to close this issue tomorrow once I've regenerated all the images; if you were struggling to understand these flags, take another look at the docs! Thanks to @agrund.

**Comment by luaduck** [comment]
Sorry for the delay, the images (for 1.9.1 and newer) have been regenerated and have this fix! Let me know if it doesn't work.

**Comment by alexdawn** [comment]
> Hi Lua,
> 
> Thanks for getting back to me.
> 
> Yep! Getting there. Passing "savename" instead led me to a NewGRF failure message. I've sorted those out and now it's loading the game.
> 
> One issue, I'm getting a "save failed" message on save now. I assume this is due to permissions.
> 
> > dbg: [sl] Game Save Failed
> > File not writeable
> > ERROR: Autosave failed
> 
> Any chance you can advise, please?

I'm getting this issue within the server console, when I try and use the save command. How did you get ottd to have the permission to write files to /config/save ?
